cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:}
      secret-key: ${AWS_SECRET_ACCESS_KEY:}
      session-token: ${AWS_SESSION_TOKEN:}
    region:
      static: ${AWS_REGION:us-east-1}
    s3:
      bucket-name: ${S3_BUCKET_NAME:despacho-grupo3-bucket}

app:
  security:
    enabled: ${APP_SECURITY_ENABLED:false}
