# =========================================================================
# CONFIGURACIÓN GENERAL DEL MICROSERVICIO
# =========================================================================
spring.application.name=despacho-service
spring.profiles.active=${SPRING_PROFILE:local}
server.port=${PORT:8080}

# =========================================================================
# CONFIGURACIÓN DE ALMACENAMIENTO TEMPORAL (REQUERIMIENTO: AWS EFS)
# =========================================================================
# Define la ruta del sistema de archivos donde se generarán y guardarán los PDFs temporalmente.
# - En local: Se creará la carpeta 'target/efs/guias' dentro del proyecto para hacer pruebas fáciles.
# - En producción: El contenedor Docker inyectará '/tmp/guias' el cual estará conectado físicamente a AWS EFS.
storage.efs.path=${EFS_TEMP_PATH:target/efs/guias}

# =========================================================================
# CONFIGURACIÓN DE CREDENCIALES DE AMAZON S3
# =========================================================================
# Nombre del contenedor de objetos (Bucket) en AWS S3 donde se moverán las guías.
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:mi-bucket-dummy}

# ID de la clave de acceso de AWS IAM necesaria para autenticar las peticiones al SDK de S3.
aws.accessKeyId=${AWS_ACCESS_KEY_ID:dummy-access-key}

# Clave secreta de AWS IAM asociada al ID anterior.
aws.secretAccessKey=${AWS_SECRET_ACCESS_KEY:dummy-secret-key}

# Token de sesión temporal de AWS (opcional, solo si usas credenciales temporales).
aws.sessionToken=${AWS_SESSION_TOKEN:}

# Región geográfica de AWS donde está alojado tu Bucket de S3 (por defecto us-east-1 / N. Virginia).
aws.region=${AWS_REGION:us-east-1}

# =========================================================================
# AZURE AD B2C — OAUTH2 RESOURCE SERVER
# =========================================================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=${AZURE_ISSUER_URI:https://dummy.b2clogin.com/dummy/v2.0/}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AZURE_JWK_SET_URI:https://dummy.b2clogin.com/dummy/discovery/v2.0/keys}

# =========================================================================
# CONFIGURACIÓN DE PERSISTENCIA Y BASE DE DATOS (H2 / MYSQL)
# =========================================================================
spring.datasource.url=jdbc:h2:mem:despachodb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
